// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_AuNJljknIA7C8-M8u5DVBAvx7fi_S-o',
    appId: '1:804902657559:android:ea151e387569a70894c652',
    messagingSenderId: '804902657559',
    projectId: 'nestneeded',
    databaseURL: 'https://nestneeded.firebaseio.com',
    storageBucket: 'nestneeded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7iRl0ZAeFIBW89dqpL-OJMwRzFjrbGK0',
    appId: '1:804902657559:ios:ef1cf1bb1dc5691994c652',
    messagingSenderId: '804902657559',
    projectId: 'nestneeded',
    databaseURL: 'https://nestneeded.firebaseio.com',
    storageBucket: 'nestneeded.appspot.com',
    iosClientId: '804902657559-7genlmk7eu6u2dp35g2lon0biarg5ahl.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiveSharingIntent',
  );
}
